name: databricks-streamlit-demo
channels:
  - conda-forge
dependencies:
  - pip
  - pyodbc
  - pandas
  - pip:
    - streamlit==0.84.0
    - black==21.6b0
    - plotly-express==0.4.1
    - plotly==5.1.0